I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 77, in script
    menu:
IOError: Couldn't find file 'got.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 77, in script
    menu:
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/ast.py", line 1628, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/exports.py", line 990, in menu
    rv = renpy.store.menu(new_items)
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/exports.py", line 1226, in display_menu
    rv = renpy.ui.interact(mouse='menu', type=type, roll_forward=roll_forward)
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/display/core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/display/core.py", line 3380, in interact_core
    renpy.audio.audio.periodic()
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/audio/audio.py", line 1060, in periodic
    six.reraise(exc[0], exc[1], exc[2])
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/audio/audio.py", line 1038, in periodic_thread_main
    periodic_pass()
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/audio/audio.py", line 979, in periodic_pass
    c.periodic()
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/audio/audio.py", line 457, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/audio/audio.py", line 73, in load
    rv = renpy.loader.load(fn)
  File "/Users/laraalley/Desktop/renpy-7.3.5-sdk/renpy/loader.py", line 576, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'got.mp3'.

Darwin-18.2.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
GoTVisualNovel 1.0
Wed Dec 11 01:06:39 2019
